//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ev_4_AE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operacion_rol
    {
        public int id { get; set; }
        public int RolId { get; set; }
        public int OperacionId { get; set; }
    
        public virtual operaciones operaciones { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
